# Generated by Django 4.1.5 on 2023-02-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmokingSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linker', models.CharField(max_length=15, null=True)),
                ('source', models.CharField(max_length=25)),
                ('birth_year', models.CharField(max_length=4)),
                ('has_smoked', models.BooleanField()),
                ('smoking_age_start', models.CharField(max_length=2, null=True)),
                ('smoking_frequency', models.CharField(max_length=25, null=True)),
                ('smoking_full_ppd', models.CharField(max_length=25, null=True)),
                ('smoking_partial_days', models.CharField(max_length=2, null=True)),
                ('smoking_partial_ppd', models.CharField(max_length=25, null=True)),
                ('smoking_former_years', models.CharField(max_length=25, null=True)),
                ('smoking_former_frequency', models.CharField(max_length=25, null=True)),
                ('smoking_former_full_ppd', models.CharField(max_length=25, null=True)),
                ('smoking_former_partial_days', models.CharField(max_length=2, null=True)),
                ('smoking_former_partial_ppd', models.CharField(max_length=25, null=True)),
                ('gender', models.CharField(max_length=25, null=True)),
                ('race', models.CharField(max_length=35, null=True)),
                ('ethnicity', models.CharField(max_length=50, null=True)),
                ('work', models.CharField(max_length=35, null=True)),
                ('income', models.CharField(max_length=35, null=True)),
                ('medical_history', models.TextField(null=True)),
                ('is_incapacitated', models.BooleanField(default=None, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmokingSurveyPrompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.TextField()),
                ('has_smoked', models.TextField()),
                ('smoking_age_start', models.TextField()),
                ('smoking_frequency', models.TextField()),
                ('smoking_full_ppd', models.TextField()),
                ('smoking_partial_days', models.TextField()),
                ('smoking_partial_ppd', models.TextField()),
                ('smoking_former_years', models.TextField()),
                ('smoking_former_frequency', models.TextField()),
                ('smoking_former_full_ppd', models.TextField()),
                ('smoking_former_partial_days', models.TextField()),
                ('smoking_former_partial_ppd', models.TextField()),
                ('gender', models.TextField()),
                ('race', models.TextField()),
                ('ethnicity', models.TextField()),
                ('work', models.TextField()),
                ('income', models.TextField()),
                ('medical_history', models.TextField()),
                ('is_incapacitated', models.TextField()),
                ('zip_code', models.TextField()),
            ],
        ),
    ]
